/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2018-07-05 01:54:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;

public final class main_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>密标接口文档</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>密级标志属性模板(json字符串)</h1>\r\n");
      out.write("<ul>\r\n");
      out.write("<li><p><b>密级level:</b>\r\n");
      out.write("\t");
 String level = new String((request.getParameter("level")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(level);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("\r\n");
      out.write("<li><p><b>保密期限duration:</b>\r\n");
      out.write("<li><p><b>1) 保密的时间长度period:</b>\r\n");
      out.write("\t");
 String period = new String((request.getParameter("period")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(period);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("\r\n");
      out.write("<li><p><b>知悉范围scope:</b>\r\n");
      out.write("<li><p><b>1) 描述形式的知悉范围description:</b>\r\n");
      out.write("\t");
 String description = new String((request.getParameter("description")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(description);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>2) 知悉人员列表staffs:</b>\r\n");
      out.write("\t");
 String staffs = new String((request.getParameter("staffs")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(staffs);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>3) 知悉部门、群 组列表groups:</b>\r\n");
      out.write("\t");
 String groups = new String((request.getParameter("groups")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(groups);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>4) 知悉单位列表units:</b>\r\n");
      out.write("\t");
 String units = new String((request.getParameter("units")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(units);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("\r\n");
      out.write("<li><p><b>定密依据basises:</b>\r\n");
      out.write("<li><p><b>1) 定密依据类型type:</b>\r\n");
      out.write("\t");
 String type = new String((request.getParameter("type")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(type);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>2) 定密依据描述description_basises:</b>\r\n");
      out.write("\t");
 String description_basises = new String((request.getParameter("description_basises")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(description_basises);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>3) 具体的定密依据的说明描述列表normalItemsnormalItems:</b>\r\n");
      out.write("\t");
 String normalItems = new String((request.getParameter("normalItems")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(normalItems);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("<li><p><b>4) 已定密(派生)事项列表derivedItems:</b>\r\n");
      out.write("\t");
 String derivedItems = new String((request.getParameter("derivedItems")).getBytes("ISO-8859-1"),"UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(derivedItems);
      out.write("\r\n");
      out.write("</p></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
